### PR TITLE
Feat: don't execute prepareIdValue if ignoreKeys is true

### PR DESCRIPTION
**Pull request by uc4w6c**
#1038

I wanted to add a test, but I couldn't do it because I couldn't find the existing class that tested prepareIdValue, and I couldn't think of a way to test it.
Please comment if you need a test. I'll take care of it.

### CODE REVIEW

**Comment by uc4w6c** [comment]
sorry. I'll fix it because the test is failing.

**Comment by nakamura-to** [comment]
Thank you for your pull request.

Currently, with PostgreSQL, the generated ID is assigned to the entity even when `ignoreGeneratedKeys` is `true`. This pull request changes that, preventing the ID from being set on the entity.

While this modification alters existing behavior, it aligns with the specification that generated IDs should not be returned to the application. Therefore, we consider this change to be acceptable.

**Comment by nakamura-to** [comment]
Close #1038

**Comment by nakamura-to** [comment]
Close #1039

**Comment by uc4w6c** [comment]
ありがとうございました！

**Pull request merged**
